name: 'gpr tool'
description: 'Run the gpr tool'
inputs:
  command:
    description: 'gpr sub-command'
    required: false
    default: list
  token:
    description: 'PAT to use'
    required: false
    default: ${{ github.token }}
  path:
    description: 'Path to packages'
    required: true
    default: 'packages'
runs:
  using: "composite"
  steps: 
    - run: |
        dotnet tool update gpr -g
        gpr ${{ inputs.command }} ${{ inputs.path }} -k ${{ inputs.token }}
      shell: bash
      env:
        DOTNET_NOLOGO: true
