on:
  push:

jobs:
  packages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: jcansdale/gpr@HEAD
      with:
        command: delete
        path: ${{ github.repository }}
        options: --force
