on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: foo
      uses: ./hello@HEAD
      with:
        who-to-greet: "Jamie"

    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
